# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - openjdk-8-jdk
      
## Fake an install, will be done in script below
install: 
  - R -e 'devtools::install_deps(pkgdir = "rcdklibs", dep = T)'

## Inspired by 
## http://jtleek.com/protocols/travis_bioc_devel/#Configuring_R_CMD_check
## https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh

script:
- R CMD build rcdklibs
- R CMD check $(ls -1t *.tar.gz | head -n 1)

