library(rJava)

#' Techincally tests SVG output
#' but more generally requires the Depict Module to be present and work
#' so it also funcitons as a check for rcdklibs >= 1.5.12
test.svgoutput <- function()
{
  
  mol <- parse.smiles("CC")
  
  #create a depiction  and write to SVG
  dg  <- .jnew("org.openscience.cdk.depict.DepictionGenerator")
  dg$withSize(512,512)$withAtomColors()
  temp1 <- paste0(tempfile(), ".svg")
  dg$depict(mol[[1]])$writeTo(temp1)
  
  #check SVG Output
  svgdata <- readChar(temp1, file.info(temp1)$size)
  checkEquals(svgdata, "<?xml version='1.0' encoding='UTF-8'?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<svg version='1.2' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='12.57mm' height='3.57mm' viewBox='0 0 12.57 3.57'>\n  <desc>Generated by the Chemistry Development Kit (http://github.com/cdk)</desc>\n  <g stroke-linecap='round' stroke-linejoin='round' stroke='#444444' stroke-width='.18' fill='#444444'>\n    <rect x='.0' y='.0' width='13.0' height='4.0' fill='#FFFFFF' stroke='none'/>\n    <g id='mol1' class='mol'>\n      <line id='mol1bnd1' class='bond' x1='4.85' y1='1.52' x2='7.72' y2='1.52'/>\n      <g id='mol1atm1' class='atom'>\n        <path d='M3.9 2.48q-.43 .0 -.66 -.25q-.23 -.25 -.23 -.71q.0 -.46 .24 -.71q.24 -.25 .67 -.25q.25 .0 .58 .08v.24q-.38 -.13 -.58 -.13q-.3 .0 -.46 .2q-.16 .2 -.16 .57q.0 .35 .17 .55q.17 .2 .48 .2q.26 .0 .56 -.16v.22q-.27 .14 -.59 .14z' stroke='none'/>\n        <path d='M.56 2.43v-1.83h.26v.77h.87v-.77h.26v1.83h-.26v-.86h-.87v.86z' stroke='none'/>\n        <path d='M2.16 2.97v-.14q.16 .06 .25 .06q.1 .0 .17 -.06q.07 -.06 .07 -.16q.0 -.23 -.32 -.23h-.06v-.1h.05q.3 .0 .3 -.21q.0 -.17 -.2 -.17q-.11 .0 -.24 .06v-.13q.13 -.04 .25 -.04q.34 .0 .34 .25q.0 .19 -.23 .28q.27 .06 .27 .29q.0 .15 -.1 .24q-.1 .09 -.28 .09q-.1 .0 -.26 -.04z' stroke='none'/>\n      </g>\n      <g id='mol1atm2' class='atom'>\n        <path d='M8.98 2.48q-.43 .0 -.66 -.25q-.23 -.25 -.23 -.71q.0 -.46 .24 -.71q.24 -.25 .67 -.25q.25 .0 .58 .08v.24q-.38 -.13 -.58 -.13q-.3 .0 -.46 .2q-.16 .2 -.16 .57q.0 .35 .17 .55q.17 .2 .48 .2q.26 .0 .56 -.16v.22q-.27 .14 -.59 .14z' stroke='none'/>\n        <path d='M9.77 2.43v-1.83h.26v.77h.87v-.77h.26v1.83h-.26v-.86h-.87v.86z' stroke='none'/>\n        <path d='M11.37 2.97v-.14q.16 .06 .25 .06q.1 .0 .17 -.06q.07 -.06 .07 -.16q.0 -.23 -.32 -.23h-.06v-.1h.05q.3 .0 .3 -.21q.0 -.17 -.2 -.17q-.11 .0 -.24 .06v-.13q.13 -.04 .25 -.04q.34 .0 .34 .25q.0 .19 -.23 .28q.27 .06 .27 .29q.0 .15 -.1 .24q-.1 .09 -.28 .09q-.1 .0 -.26 -.04z' stroke='none'/>\n      </g>\n    </g>\n  </g>\n</svg>\n")
}


